                       LACAL HOSTS
###getall
GET http://localhost:3000/contactS/

###getone
GET http://localhost:3000/contactS/ 

###gcreate contact
POST http://localhost:3000/contactS  HTTP/1.1
Content-Type: application/json


###update by id
PUT http://localhost:3000/contactS/ HTTP/1.1
Content-Type: application/json



###delete id
DELETE http://localhost:3000/contactS/ HTTP/1.1